spring.application.name=portfolio-tracker-backend

# Server
server.port=${PORT:8080}

# Logging
logging.level.org.hibernate.SQL=WARN

# Database configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}&prepareThreshold=0
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# HikariCP - disable prepared statements for PgBouncer
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=1

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect