package com.yingkai.financial.portfolio_tracker_backend.entity;

public enum FundType {
    VOO("VOO", "Vanguard S&P 500 ETF"),
    VTI("VTI", "Vanguard Total Stock Market ETF"),
    BND("BND", "Vanguard Total Bond Market ETF"),
    VNQ("VNQ", "Vanguard Real Estate ETF"),
    QQQ("QQQ", "Invesco QQQ Trust"),
    VEA("VEA", "Vanguard FTSE Developed Markets ETF"),
    VTSAX("VTSAX", "Vanguard Total Stock Market Index Fund Admiral Shares"),
    VFIAX("VFIAX", "Vanguard 500 Index Fund Admiral Shares"),
    FXAIX("FXAIX", "Fidelity 500 Index Fund"),
    VTIAX("VTIAX", "Vanguard Total International Stock Index Fund Admiral Shares"),
    SPAXX("SPAXX", "Fidelity Government Money Market Fund"),
    FZCXX("FZCXX", "Fidelity Government Money Market Fund Premium Class"),
    VBTLX("VBTLX", "Vanguard Total Bond Market Index Fund Admiral Shares"),
    VINIX("VINIX", "Vanguard Institutional Index Fund"),
    AGTHX("AGTHX", "American Funds The Growth Fund of America Class A"),
    GFACX("GFACX", "American Funds The Growth Fund of America Class C"),
    NVDA("NVDA", "NVIDIA Corporation"),
    GOOGL("GOOGL", "Alphabet Inc. Class A"),
    GOOG("GOOG", "Alphabet Inc. Class C"),
    AAPL("AAPL", "Apple Inc."),
    MSFT("MSFT", "Microsoft Corporation"),
    AMZN("AMZN", "Amazon.com Inc."),
    TSM("TSM", "Taiwan Semiconductor Manufacturing Company Limited"),
    AVGO("AVGO", "Broadcom Inc."),
    META("META", "Meta Platforms Inc."),
    TSLA("TSLA", "Tesla Inc."),
    JPM("JPM", "JPMorgan Chase & Co."),
    WMT("WMT", "Walmart Inc."),
    BRK_A("BRK.A", "Berkshire Hathaway Inc. Class A"),
    BRK_B("BRK.B", "Berkshire Hathaway Inc. Class B"),
    LLY("LLY", "Eli Lilly and Company"),
    XOM("XOM", "Exxon Mobil Corporation"),
    V("V", "Visa Inc."),
    ASML("ASML", "ASML Holding N.V."),
    JNJ("JNJ", "Johnson & Johnson"),
    BAC("BAC", "Bank of America Corporation"),
    ORCL("ORCL", "Oracle Corporation"),
    MU("MU", "Micron Technology Inc."),
    AMD("AMD", "Advanced Micro Devices Inc."),
    MA("MA", "Mastercard Incorporated"),
    COST("COST", "Costco Wholesale Corporation"),
    NFLX("NFLX", "Netflix Inc."),
    CAT("CAT", "Caterpillar Inc."),
    CVX("CVX", "Chevron Corporation"),
    ABBV("ABBV", "AbbVie Inc."),
    CSCO("CSCO", "Cisco Systems Inc."),
    GS("GS", "The Goldman Sachs Group Inc."),
    PLTR("PLTR", "Palantir Technologies Inc."),
    HD("HD", "The Home Depot Inc."),
    INTC("INTC", "Intel Corporation"),
    PG("PG", "The Procter & Gamble Company"),
    C("C", "Citigroup Inc."),
    MS("MS", "Morgan Stanley"),
    LRCX("LRCX", "Lam Research Corporation"),
    BABA("BABA", "Alibaba Group Holding Limited"),
    KO("KO", "The Coca-Cola Company"),
    UNH("UNH", "UnitedHealth Group Incorporated"),
    HSBC("HSBC", "HSBC Holdings plc"),
    AMAT("AMAT", "Applied Materials Inc."),
    AZN("AZN", "AstraZeneca PLC"),
    GE("GE", "GE Aerospace"),
    NVS("NVS", "Novartis AG"),
    MRK("MRK", "Merck & Co. Inc."),
    GEV("GEV", "GE Vernova Inc."),
    TM("TM", "Toyota Motor Corporation"),
    RTX("RTX", "RTX Corporation"),
    WFC("WFC", "Wells Fargo & Company"),
    RY("RY", "Royal Bank of Canada"),
    SHEL("SHEL", "Shell plc"),
    IBM("IBM", "International Business Machines Corporation"),
    PM("PM", "Philip Morris International Inc."),
    KLAC("KLAC", "KLA Corporation"),
    LIN("LIN", "Linde plc"),
    AXP("AXP", "American Express Company"),
    TMUS("TMUS", "T-Mobile US Inc."),
    ANET("ANET", "Arista Networks Inc."),
    MCD("MCD", "McDonald's Corporation"),
    TXN("TXN", "Texas Instruments Incorporated"),
    PEP("PEP", "PepsiCo Inc."),
    SAP("SAP", "SAP SE"),
    MUFG("MUFG", "Mitsubishi UFJ Financial Group Inc."),
    BHP("BHP", "BHP Group Limited"),
    TTE("TTE", "TotalEnergies SE"),
    VZ("VZ", "Verizon Communications Inc."),
    TMO("TMO", "Thermo Fisher Scientific Inc."),
    TD("TD", "The Toronto-Dominion Bank"),
    NEE("NEE", "NextEra Energy Inc."),
    APH("APH", "Amphenol Corporation"),
    ARM("ARM", "Arm Holdings plc"),
    AMGN("AMGN", "Amgen Inc."),
    DIS("DIS", "The Walt Disney Company"),
    ADI("ADI", "Analog Devices Inc."),
    T("T", "AT&T Inc."),
    SAN("SAN", "Banco Santander S.A."),
    TJX("TJX", "The TJX Companies Inc."),
    NVO("NVO", "Novo Nordisk A/S"),
    CRM("CRM", "Salesforce Inc."),
    BA("BA", "The Boeing Company"),
    SHOP("SHOP", "Shopify Inc."),
    GILD("GILD", "Gilead Sciences Inc."),
    BLK("BLK", "BlackRock Inc."),
    SCHW("SCHW", "The Charles Schwab Corporation"),
    ABT("ABT", "Abbott Laboratories"),
    ISRG("ISRG", "Intuitive Surgical Inc.");

    private final String ticker;
    private final String name;

    FundType(String ticker, String name) {
        this.ticker = ticker;
        this.name = name;
    }

    public String getTicker() {
        return ticker;
    }

    public String getName() {
        return name;
    }
}
